CREATE TABLE [dbo].[SACH] (
    [MAS] NCHAR (10)       NOT NULL,
	[MANXB]    NCHAR (10)    NOT NULL,
    [TENS] NVARCHAR(255)       NOT NULL,
    [TENTG] NVARCHAR(255)  NOT NULL,
    [LOAI] NVARCHAR(255)      NOT NULL,
	[SOLUONG] INT      NOT NULL,
	[GIANHAP] INT      NOT NULL,
	[GIABAN] INT      NOT NULL,
    PRIMARY KEY CLUSTERED ([MAS] ASC)
);
CREATE TABLE [dbo].[DAILY] (
    [MADL]     NCHAR (10)            NOT NULL,
    [TENDL]       NVARCHAR (50) NOT NULL,
    [DIACHI]      NVARCHAR (50) NOT NULL,
    [SDT]      INT     NOT NULL,
	[SOTIENNO] INT    NOT NULL,
    PRIMARY KEY CLUSTERED ([MADL] ASC)
);
CREATE TABLE [dbo].[NXB] (
    [MANXB]    NCHAR (10)    NOT NULL,
    [TENNXB]   NVARCHAR (50) NOT NULL,
    [DIACHI]  NVARCHAR(255)           NOT NULL,
    [SDT]  INT        NOT NULL,
	[STK]  NVARCHAR (50)       NOT NULL,
    PRIMARY KEY CLUSTERED ([MANXB] ASC)
);
 --Phiếu nhập
CREATE TABLE [dbo].[PHIEUNHAPSACH] (
    [MAPNS]   INT      IDENTITY (1, 1) NOT NULL,
    [MANXB]    NCHAR (10)    NOT NULL,	
    [NGUOIGS]   NVARCHAR (255) NOT NULL,
    [NGAYNHAP]  DATETIME      NOT NULL,
    [THANHTIEN]    INT           NOT NULL,
    PRIMARY KEY CLUSTERED ([MAPNS] ASC)
);
--Chi tiết phiếu nhập 
CREATE TABLE [dbo].[CTPNS] (
    [MAPNS]   INT      NOT NULL,
    [MAS] NCHAR (10)       NOT NULL,
	[SOLUONGN] INT    NOT NULL,
    [TONG] INT    NOT NULL,
    PRIMARY KEY CLUSTERED ([MAPNS] ASC,[MAS] ASC)
);
-- Phiếu xuất sách cho đại lý
CREATE TABLE [dbo].[PHIEUXUATSACH] (
    [MAPXS]   INT     IDENTITY (1, 1) NOT NULL,
	[MADL]     NCHAR (10)            NOT NULL,
	[NGUOINS]   NVARCHAR (255) NOT NULL,
    [NGAYXUAT]  DATETIME      NOT NULL,
    [THANHTIEN]    INT           NOT NULL,
    PRIMARY KEY CLUSTERED ([MAPXS] ASC)
);
--Chi tiết phiếu xuất
CREATE TABLE [dbo].[CTPXS] (
    [MAPXS]   INT      NOT NULL,
    [MAS] NCHAR (10)       NOT NULL,
	[SOLUONGN] INT    NOT NULL,
    [TONG] INT    NOT NULL,
    PRIMARY KEY CLUSTERED ([MAPXS] ASC,[MAS] ASC)
);
-- trả tiền cho mình
CREATE TABLE [dbo].[PHIEUTRATIEN] (
    [MATK]   INT      IDENTITY (1, 1) NOT NULL,
	[MADL]     NCHAR (10)            NOT NULL,
    [NGAY]  DATETIME      NOT NULL,
    [SOTIENNO]    INT           NOT NULL,
	[TRANGTHAI] int,
    PRIMARY KEY CLUSTERED ([MATK] ASC)
);

CREATE TABLE [dbo].[CTPTT] (
    [MATK]   INT  NOT NULL,
	[MAS]     NCHAR (10)            NOT NULL,
    [SOLUONGN]  INT     NOT NULL,
    [TONG]    INT           NOT NULL,
    PRIMARY KEY CLUSTERED ([MATK] ASC,[MAS] ASC)
);
--thống kê tồn kho
CREATE TABLE [dbo].[TKTK] (
    [MAKHO]   INT      IDENTITY (1, 1) NOT NULL,
	[MAS] NCHAR (10)       NOT NULL,
	[NGAY]  DATETIME      NOT NULL,
    [SLTON] INT    NOT NULL,
    PRIMARY KEY CLUSTERED ([MAKHO] ASC)
);

--số lượng đại lý
CREATE TABLE [dbo].[SLDL] (
    [MADL]     NCHAR (10)            NOT NULL,
	[MAS] NCHAR (10)       NOT NULL,
    [SLTON] INT    NOT NULL,
    PRIMARY KEY CLUSTERED ([MADL] ASC,[MAS] ASC)
)
--doanh thu và số tiền hoàn lại cho nxb
CREATE TABLE [dbo].[DOANHTHU] (
    [MADT]    INT      IDENTITY (1, 1) NOT NULL,
	[MANXB]    NCHAR (10)    NOT NULL,
    [NGAY] DATETIME    NOT NULL,
	[SOTIENNXB] INT    NOT NULL,
    PRIMARY KEY CLUSTERED ([MADT] ASC)
)

ALTER TABLE SACH ADD FOREIGN KEY (MANXB) REFERENCES NXB(MANXB)
ALTER TABLE PHIEUNHAPSACH ADD FOREIGN KEY (MANXB) REFERENCES NXB(MANXB)
ALTER TABLE CTPNS ADD FOREIGN KEY (MAPNS) REFERENCES PHIEUNHAPSACH(MAPNS)
ALTER TABLE CTPNS ADD FOREIGN KEY (MAS) REFERENCES SACH(MAS)
ALTER TABLE PHIEUXUATSACH ADD FOREIGN KEY (MADL) REFERENCES DAILY(MADL)
ALTER TABLE CTPXS ADD FOREIGN KEY (MAPXS) REFERENCES PHIEUXUATSACH(MAPXS)
ALTER TABLE CTPXS ADD FOREIGN KEY (MAS) REFERENCES SACH(MAS)
ALTER TABLE PHIEUTRATIEN ADD FOREIGN KEY (MADL) REFERENCES DAILY(MADL)
ALTER TABLE CTPTT ADD FOREIGN KEY (MATK) REFERENCES PHIEUTRATIEN(MATK)
ALTER TABLE CTPTT ADD FOREIGN KEY (MAS) REFERENCES SACH(MAS)
ALTER TABLE SLDL ADD FOREIGN KEY (MADL) REFERENCES DAILY(MADL)
ALTER TABLE SLDL ADD FOREIGN KEY (MAS) REFERENCES SACH(MAS)
ALTER TABLE TKTK ADD FOREIGN KEY (MAS) REFERENCES SACH(MAS)
ALTER TABLE DOANHTHU ADD FOREIGN KEY (MANXB) REFERENCES NXB(MANXB)


