//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOANHTHU
    {
        public int MADT { get; set; }
        public string MANXB { get; set; }
        public System.DateTime NGAY { get; set; }
        public int SOTIENNXB { get; set; }
    
        public virtual NXB NXB { get; set; }
    }
}
