//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUXUATSACH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIEUXUATSACH()
        {
            this.CTPXS = new HashSet<CTPX>();
        }
    
        public int MAPXS { get; set; }
        public string MADL { get; set; }
        public string NGUOINS { get; set; }
        public System.DateTime NGAYXUAT { get; set; }
        public int THANHTIEN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTPX> CTPXS { get; set; }
        public virtual DAILY DAILY { get; set; }
    }
}
