//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUTRATIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIEUTRATIEN()
        {
            this.DOANHTHUs = new HashSet<DOANHTHU>();
        }
    
        public int MATK { get; set; }
        public int MAPXS { get; set; }
        public string MADL { get; set; }
        public System.DateTime NGAY { get; set; }
        public int SOTIENTRA { get; set; }
        public int SOTIENNO { get; set; }
        public string TRANGTHAI { get; set; }
    
        public virtual DAILY DAILY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOANHTHU> DOANHTHUs { get; set; }
        public virtual PHIEUXUATSACH PHIEUXUATSACH { get; set; }
    }
}
