//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SLDL
    {
        public string MADL { get; set; }
        public string MAS { get; set; }
        public int SLTON { get; set; }
    
        public virtual DAILY DAILY { get; set; }
        public virtual DAILY DAILY1 { get; set; }
        public virtual SACH SACH { get; set; }
    }
}
